[package]
name = "tyu-core"
version.workspace = true
edition.workspace = true

[dependencies]
tyu-types.workspace = true
tyu-protocol.workspace = true
serde.workspace = true
postcard.workspace = true
tokio.workspace = true
tokio-util.workspace = true
quinn.workspace = true
rustls.workspace = true
rcgen.workspace = true
sha2.workspace = true
blake3.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
mdns-sd.workspace = true
cap-std.workspace = true
directories.workspace = true
hex.workspace = true
uuid.workspace = true
getrandom = "0.3"
zeroize = { version = "1", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61", features = ["Win32_Security_Cryptography", "Win32_Foundation"] }

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(windows)'.dev-dependencies]
junction = "2"
